 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/npcs", type: :request do
  
  # Npc. As you add validations to Npc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Npc.create! valid_attributes
      get npcs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      npc = Npc.create! valid_attributes
      get npc_url(npc)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_npc_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      npc = Npc.create! valid_attributes
      get edit_npc_url(npc)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Npc" do
        expect {
          post npcs_url, params: { npc: valid_attributes }
        }.to change(Npc, :count).by(1)
      end

      it "redirects to the created npc" do
        post npcs_url, params: { npc: valid_attributes }
        expect(response).to redirect_to(npc_url(Npc.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Npc" do
        expect {
          post npcs_url, params: { npc: invalid_attributes }
        }.to change(Npc, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post npcs_url, params: { npc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested npc" do
        npc = Npc.create! valid_attributes
        patch npc_url(npc), params: { npc: new_attributes }
        npc.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the npc" do
        npc = Npc.create! valid_attributes
        patch npc_url(npc), params: { npc: new_attributes }
        npc.reload
        expect(response).to redirect_to(npc_url(npc))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        npc = Npc.create! valid_attributes
        patch npc_url(npc), params: { npc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested npc" do
      npc = Npc.create! valid_attributes
      expect {
        delete npc_url(npc)
      }.to change(Npc, :count).by(-1)
    end

    it "redirects to the npcs list" do
      npc = Npc.create! valid_attributes
      delete npc_url(npc)
      expect(response).to redirect_to(npcs_url)
    end
  end
end
